---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  LOKI_URL: "http://loki.default.svc.cluster.local:3100/loki/api/v1/push"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://tempo.default.svc.cluster.local:9411"
  PRODUCT_SERVICE_URL: "http://product-service.default.svc.cluster.local:8081"
  CLIENT_SERVICE_URL: "http://client-service.default.svc.cluster.local:8082"
