version: '4'
services:

  mysql-product:
    image: mysql:8.3.0
    container_name: mysql-product
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql-product:/var/lib/mysql
      - ./docker/mysql/initProduct.sql:/docker-entrypoint-initdb.d/initProduct.sql

  mysql-client:
    image: mysql:8.3.0
    container_name: mysql-client
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3308:3306"
    volumes:
      - ./data/mysql-client:/var/lib/mysql
      - ./docker/mysql/initProduct.sql:/docker-entrypoint-initdb.d/initClient.sql