version: '4'
services:

  mysql-product:
    image: mysql:8.3.0
    container_name: mysql-product
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql-product:/var/lib/mysql
      - ./docker/mysql/initProduct.sql:/docker-entrypoint-initdb.d/initProduct.sql

  mysql-client:
    image: mysql:8.3.0
    container_name: mysql-client
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3308:3306"
    volumes:
      - ./data/mysql-client:/var/lib/mysql
      - ./docker/mysql/initClient.sql:/docker-entrypoint-initdb.d/initClient.sql

  mysql-quotation:
    image: mysql:8.3.0
    container_name: mysql-quotation
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3309:3306"
    volumes:
      - ./data/mysql-quotation:/var/lib/mysql
      - ./docker/mysql/initQuotation.sql:/docker-entrypoint-initdb.d/initQuotation.sql

  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9001:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
      - ./docker/themes/:/opt/keycloak/themes/
    depends_on:
      - keycloak-mysql